version: '3.8'

services:
  mongodb:
    image: mongo:7.0.2-jammy
    container_name: db-metrics-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  postgres:
    image: postgres:16.0-alpine3.18
    container_name: db-metrics-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db-metrics-postgres
