// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package bridge

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Book struct {
	ID       uuid.UUID
	Title    string
	Author   string
	Genre    string
	Synopsis sql.NullString
}

type Review struct {
	ID      uuid.UUID
	UserID  uuid.NullUUID
	BookID  uuid.NullUUID
	Rating  float64
	Comment sql.NullString
}

type User struct {
	ID          uuid.UUID
	Name        string
	Email       string
	Preferences pqtype.NullRawMessage
}
